src/Entity/Booking.php
<?php

namespace App\Entity;
use Symfony\Component\Validator\Constraints as Assert;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\BookingRepository")
 * @ORM\HasLifecycleCallbacks()
 */
class Booking
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="bookings")
     * @ORM\JoinColumn(nullable=false)
     */
    private $booker;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Ad", inversedBy="bookings")
     * @ORM\JoinColumn(nullable=false)
     */
    private $ad;

    /**
     * @ORM\Column(type="datetime")
     * @Assert\Type("\DateTimeInterface")
     * @Assert\GreaterThan("today", message ="Arrivel date must be after of NOW !!", groups = {"front"})
     * 
     */
    private $startDate;

    /**
     * @ORM\Column(type="datetime")
     * @Assert\Type("\DateTimeInterface")
     * @Assert\GreaterThan(propertyPath = "startDate", message ="Finish date must be after of Arrivel Date !!")
     */
    private $endDate;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\Column(type="float")
     */
    private $amount;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $comment;

    /**
     * callback appele a chaque fois qu'on cree une reservation 
     * @ORM\PrePersist
     * @ORM\PreUpdate
     * 
     * @return void
     */
    public function prePersist()  {
        if (empty($this->createdAt))  {
            $this->createdAt = new \DateTime() ;
        }

        if (empty($this->amount))  {
            // prix de l'annonce * nombre de jour 

            $this->amount =  $this->ad->getPrice() * $this->getDuration()  ;

        }
    }

    /**
     * Undocumented function
     *
     * @return boolean
     */
    public function isBookableDates()  {
             // 1 - il faut connaitre les dates qui sont impossibles pour l'annonce 
             $notAvailableDays = $this->ad->getNotAvailableDays() ;
             // 2- il faut comparer les dates choisies avec les dates impossibles 

             $bookingDays   = $this->getDays() ;

             $formatDay     = function($day)  {
                return $day->format('Y-m-d')  ;
            }  ;

             //Tableau qui contient des chaines des caracteres de mes journees 
             $days          = array_map($formatDay, $bookingDays)  ;
             $notAvailable  = array_map($formatDay, $notAvailableDays)  ;

            foreach($days as $day)  {
                if (array_search($day, $notAvailable) !== false )  return false ; 
            }

            return true ; 
    }

    /**
     * Permet de recuperer un tableau des journees qui correspond a ma reservation 
     *
     * @return array un Tableau d'objet DateTime reprsentant les jours de reservations 
     */
    public function getDays()  {

        $resultat = range(
            $this->startDate->getTimestamp(),
            $this->endDate->getTimestamp() ,
            24 * 60 * 60 
        )  ;

        $days = array_map(function ($dayTimestamp)  {
            return new \DateTime(date('Y-m-d', $dayTimestamp))  ;
        } , $resultat)  ;

        return $days  ;

    }

    public function getDuration()  {
        $diff = $this->endDate->diff($this->startDate)  ;
        return $diff->days ;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getBooker(): ?User
    {
        return $this->booker;
    }

    public function setBooker(?User $booker): self
    {
        $this->booker = $booker;

        return $this;
    }

    public function getAd(): ?Ad
    {
        return $this->ad;
    }

    public function setAd(?Ad $ad): self
    {
        $this->ad = $ad;

        return $this;
    }

    public function getStartDate(): ?\DateTimeInterface
    {
        return $this->startDate;
    }

    public function setStartDate(\DateTimeInterface $startDate): self
    {
        $this->startDate = $startDate;

        return $this;
    }

    public function getEndDate(): ?\DateTimeInterface
    {
        return $this->endDate;
    }

    public function setEndDate(\DateTimeInterface $endDate): self
    {
        $this->endDate = $endDate;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getAmount(): ?float
    {
        return $this->amount;
    }

    public function setAmount(float $amount): self
    {
        $this->amount = $amount;

        return $this;
    }

    public function getComment(): ?string
    {
        return $this->comment;
    }

    public function setComment(?string $comment): self
    {
        $this->comment = $comment;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use Cocur\Slugify\Slugify;
use Symfony\Component\Validator\Constraints as Assert;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @ORM\HasLifecycleCallbacks
 * @UniqueEntity(
 *   fields = {"email"},
 *   message = "Other User registered with this email, Plz change it  !"
 * )
 */
class User implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message = "First Name can not be empty")
     */
    private $firstName;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message = "Last Name can not be empty")
     */
    private $lastName;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Email(message = "Write a valid Email")
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\Url(message = "Enter a valid Url for your Avatar !")
     */
    private $picture;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $hash;

    /**
     *@Assert\EqualTo(propertyPath="hash", message = "Confirm your Password Plz !")
     */
    public $passwordConfirm ;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min=10, minMessage="Introduction  must be at least 10 charachter !")
     */
    private $introduction;


    /**
     * @ORM\Column(type="text")
     * @Assert\Length(min=100, minMessage="Description  must be at least 100 charachter !")
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Ad", mappedBy="author")
     */
    private $ads;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Role", mappedBy="users")
     */
    private $userRoles;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Booking", mappedBy="booker")
     */
    private $bookings;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Comment", mappedBy="author", orphanRemoval=true)
     */
    private $comments;

    public function getFullName()  {
        return "{$this->getFirstName() } {$this->getLastName() }"  ;
    }

    /**
     * Allow initialize slug
     *@ORM\PrePersist
     *@ORM\PreUpdate 
     * @return void
     */
    public function initializeSlug()  {
        if (empty($this->slug))  {
            $slugify= new Slugify() ;
            $this->slug = $slugify->slugify($this->firstName . ' ' . $this->lastName) ;
        }
    }

    public function __construct()
    {
        $this->ads = new ArrayCollection();
        $this->userRoles = new ArrayCollection();
        $this->bookings = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(string $lastName): self
    {
        $this->lastName = $lastName;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(?string $picture): self
    {
        $this->picture = $picture;

        return $this;
    }

    public function getHash(): ?string
    {
        return $this->hash;
    }

    public function setHash(string $hash): self
    {
        $this->hash = $hash;

        return $this;
    }

    public function getIntroduction(): ?string
    {
        return $this->introduction;
    }

    public function setIntroduction(string $introduction): self
    {
        $this->introduction = $introduction;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    /**
     * @return Collection|Ad[]
     */
    public function getAds(): Collection
    {
        return $this->ads;
    }

    public function addAd(Ad $ad): self
    {
        if (!$this->ads->contains($ad)) {
            $this->ads[] = $ad;
            $ad->setAuthor($this);
        }

        return $this;
    }

    public function removeAd(Ad $ad): self
    {
        if ($this->ads->contains($ad)) {
            $this->ads->removeElement($ad);
            // set the owning side to null (unless already changed)
            if ($ad->getAuthor() === $this) {
                $ad->setAuthor(null);
            }
        }

        return $this;
    }

    public function getRoles()
        {
        

         $roles = $this->userRoles->map(function ($role) {
                return $role->getTitle()  ;
         })->toArray() ;

         $roles []  = 'ROLE_USER' ;

          return $roles;
        }
    public function getPassword() 
      {
          return $this->hash ;
      }

    public function getSalt()  {}

    public function getUsername()  {
        return $this->email ;
    }
    public function eraseCredentials()  {}

    /**
     * @return Collection|Role[]
     */
    public function getUserRoles(): Collection
    {
        return $this->userRoles;
    }

    public function addUserRole(Role $userRole): self
    {
        if (!$this->userRoles->contains($userRole)) {
            $this->userRoles[] = $userRole;
            $userRole->addUser($this);
        }

        return $this;
    }

    public function removeUserRole(Role $userRole): self
    {
        if ($this->userRoles->contains($userRole)) {
            $this->userRoles->removeElement($userRole);
            $userRole->removeUser($this);
        }

        return $this;
    }

    /**
     * @return Collection|Booking[]
     */
    public function getBookings(): Collection
    {
        return $this->bookings;
    }

    public function addBooking(Booking $booking): self
    {
        if (!$this->bookings->contains($booking)) {
            $this->bookings[] = $booking;
            $booking->setBooker($this);
        }

        return $this;
    }

    public function removeBooking(Booking $booking): self
    {
        if ($this->bookings->contains($booking)) {
            $this->bookings->removeElement($booking);
            // set the owning side to null (unless already changed)
            if ($booking->getBooker() === $this) {
                $booking->setBooker(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setAuthor($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->contains($comment)) {
            $this->comments->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getAuthor() === $this) {
                $comment->setAuthor(null);
            }
        }

        return $this;
    }
}

src/Controller/BookingController.php
<?php

namespace App\Controller;

use App\Entity\Ad;
use App\Entity\Booking;
use App\Entity\Comment;
use App\Form\BookingType;
use App\Form\CommentType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class BookingController extends AbstractController
{
    /**
     * @Route("/ads/{slug}/book", name="booking_create")
     * @IsGranted("ROLE_USER")
     */
    public function book(Ad $ad, Request $request, EntityManagerInterface $em)
    {
        $booking = new Booking() ;
        $form = $this->createForm(BookingType::class, $booking) ; 

        $form->handleRequest($request) ;   // demande de formulaire la requete passer

        if ($form->isSubmitted() && $form->isValid())  {

            $user = $this->getUser() ; 

            $booking->setBooker($user)
                    ->setAd($ad)  ;

                    // Si les dates ne sont pas disponibles Message d'error 
                        if(!$booking->isBookableDates())  {
                            $this->addFlash(
                                'warning',
                                "selected dates not available ! Choose other date PLZ !"
                            );
                        }   else {
                             // si non enregistrement et redirection 
                            $em->persist($booking) ;
                            $em->flush()  ;
                
                            return $this->redirectToRoute('booking_show', ['id' => $booking->getId(), 
                                'withAlert' => true 
                            ])  ;
                        }
         }
                   
           
        return $this->render('booking/book.html.twig', [
            'ad' => $ad,
            'form' => $form->createView()
        ]);
    }

    /**
     * Permet d'afficher la page d'une reservation 
     *@Route("/booking/{id}" , name = "booking_show")
     * @param Booking $booking
     * @param Request $request
     * @param EntityManagerInterface $em
     * @return Response
     */
    public function show(Booking $booking, Request $request, EntityManagerInterface $em)  {

        $comment = new Comment()  ;

        $form = $this-> createForm(CommentType::class, $comment) ;

        $form->handleRequest($request)  ;

        if ($form->isSubmitted() && $form->isValid())  {

            $comment->setAd($booking->getAd())   // lier le commentaire a une annonce
                    ->setAuthor($this->getUser())  ;  // lier aussi le commentaire a l'utilisateur connecter 

            $em->persist($comment)  ;
            $em->flush()  ;

            $this->addFlash(
                'success', 
                "your comment has been taken into account"
            ) ; 
        }


            return $this->render('booking/show.html.twig', [
                'booking' => $booking,
                'form'    => $form->createView()
            ]) ;
    }


}

templates/booking/book.html.twig
{% extends 'base.html.twig' %}

{% block title %}Book the ad {{ ad.title }} {% endblock %}

{% block stylesheets %}
     <link rel="stylesheet" 
     href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css"  />


{% endblock %}

{% block body %}
<div class="container">
    <h1>Book the ad <em>{{ ad.title }} </em></h1>
    <p> you are about to reserve the property of <strong>{{ ad.author.fullName }}</strong> 
    tell us all and we take care of the rest
    </p>

         {{ form_start(form) }}

         <div class="alert alert-light">
             <h2 class="h4">Select your interested Date !</h2>
             <div class="row">
                <div class="col">
                   {{ form_row(form.startDate) }}
                </div>

                <div class="col">
                    {{ form_row(form.endDate) }}
                </div>

             </div>
                    <h4 class="mt-2"> Amount of Stay : <span id="amount"> .....</span>&euro;</h4>

                      <span id="days">0</span> night(s) for {{ ad.price | number_format(2, ',', ' ') }}&euro;  per night 

       
                     <h4 class="mt-4">Do you have a comment ?</h4>
                        {{ form_row(form.comment) }}
         </div>

  

                 <h2>  you have finished? accommodation for work ? whatever, we're with you ?</h2>

                 <button type="submit" class="btn btn-success">I Book !</button>

         {{ form_end(form) }}
</div>

{% endblock %}

{% block javascripts %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js">
    </script>

    <script>
         $(document).ready(function()  {
             $('#booking_startDate, #booking_endDate').datepicker({
                 format: 'dd/mm/yyyy', 
                 datesDisabled : [
                     {% for day in ad.notAvailableDays %}
                        "{{ day.format('d/m/Y') }}", 
                     {% endfor %}
                 ] ,
                 startDate : new Date()
             });

             $('#booking_startDate, #booking_endDate').on('change', calculateAmount)
           }) ;

           function calculateAmount()  {
               // on chope les dates
               const endDate = new Date($('#booking_endDate').val().replace(/(\d+)\/(\d+)\/(\d{4})/, 
               '$3-$2-$1'))  ;
               //07/04/2020
            // utiliser expression reguiliere  
            // (\d+)\/(\d+)\/(\d{4})
               //2020-04-07
               const startDate = new Date($('#booking_startDate').val().replace(/(\d+)\/(\d+)\/(\d{4})/, 
               '$3-$2-$1'))  ;

               if (startDate && endDate && startDate < endDate )  {

                   const DAY_TIME = 24 * 60 * 60 * 1000 ;
                   const interval = endDate.getTime()  - startDate.getTime()  ;
                   const days = interval / DAY_TIME ;

                   const amount = days * {{ ad.price }}  ;

                   $('#days').text(days)  ;
                   $('#amount').text(amount.toLocaleString('fr-FR'))  ;
               }
           }
    </script>
{% endblock %}

templates/booking/show.html.twig
{% extends 'base.html.twig' %}

{% block title %} Booking number {{ booking.id }}{% endblock %}

{% block body %}

{% set ad = booking.ad %}
{% set author = ad.author %}
   <div class="container">
      <h1 class="my-5">Your Booking number {{ booking.id }}</h1>

      {% if app.request.query.get('withAlert') %}
            <div class="alert alert-success">
                <h4 class="alert-heading">Well done !</h4>
                <p>Your Bookin with 
                   <strong><a href="{{ path('user_show', {'slug' : author.slug })}}">{{ author.fullName }}</a></strong>
                   for ad 
                   <strong>
                     <a href="{{ path('ads_show', {'slug': ad.slug }) }}">{{ ad.title }}</a>
                   </strong>
                   
                    has been taken into account
                </p>
            </div>
      {% endif %}

      <div class="row">
         <div class="col">
             <div class="alert alert-light">
                <h2>Details</h2>

                <dl class="row">
                   
                    <dt class="col-md-4">Number</dt>
                    <dd class="col-md-8">{{ booking.id }}</dd>
                    <dt class="col-md-4">Arrivel Date</dt>
                    <dd class="col-md-8">{{ booking.startDate | date('d/m/Y')}}</dd>
                    <dt class="col-md-4">End Date</dt>
                    <dd class="col-md-8">{{ booking.endDate | date('d/m/Y')}}</dd>
                    <dt class="col-md-4">Night Number</dt>
                    <dd class="col-md-8">{{ booking.duration }}</dd>
                    <dt class="col-md-4">Amount </dt>
                    <dd class="col-md-8">{{ booking.amount | number_format(2 , ',', ' ') }}&euro;</dd>
                    <dt class="col-md-4">Comment</dt>
                    <dd class="col-md-8">{{ booking.comment | default('No Comment ! ') }}</dd>       
                </dl>

                <hr>
                <h2 class="alert-heading">Your Host</h2>

                <div class="row mb-3">
                    <div class="col-3">
                        <img src="{{ author.picture }}" class="avatar avatar-medium" alt="{{ author.fullName }}">
                    </div>
                    <div class="col-9">
                        <h4>
                            <a href="{{ path('user_show', {'slug': author.slug }) }}">{{ author.fullName }}</a>
                        </h4>

                        <span class="badge badge-primary">
                          {{ author.ads | length }} Ads
                        </span>
                    </div>
                </div>
                {{ author.description | raw }}

                <a href="{{ path('user_show', {'slug': author.slug }) }}" class="btn btn-primary">More info about {{ author.firstName }}</a>
             </div>

             <div class="alert alert-light" id="comment">
                <h2 class="alert-heading">Your opinion matters to us </h2>

                {% if date() > date(booking.endDate) %}
                    {% set comment = booking.ad.commentFromAuthor(app.user) %}

                      {% if comment is not null %}
                            <blockquote>
                                {{ comment.content}}
                            </blockquote>
                            <strong>Note : </strong>
                            {% include 'partials/rating.html.twig' with { 'rating':comment.rating }%}
                       {% else %}
                         {{ form_start(form) }}
                         {{ form_widget(form) }}
                         <button type="submit" class="btn btn-success">Confirm your Comment</button>
                         {{ form_end(form) }}
                       {% endif %}
                    
                {% else %}
                    <p>You will not be able to rate this announcement until your trip is complete!</p>
                {% endif %}
               
             </div>
         </div>
         <div class="col">
             <div class="alert alert-light">
                <h2 class="alert-heading">Your accommodation</h2>
                <h4>
                    <a href="{{ path('ads_show', {'slug' : ad.slug })}}">{{ ad.title }}</a>
                </h4>

                <img src="{{ ad.coverImage }}" class="img-fluid" alt="Picture of {{ ad.title }}">

                {{ ad.content | raw }}

                 <a href="{{ path('ads_show', {'slug': ad.slug }) }}" class="btn btn-primary">More info</a>
             </div>
         </div>
      </div>
   </div>

{% endblock %}